<?php

namespace Distr;

use Composer\Script\Event;

class Loader
{
    public static function loadConfigs(Event $event)
    {
        $configs = glob(__DIR__ . '/config/*.php');

        $installer = new Installer($event->getIO());

        foreach ($configs as $config) {
            if ( ! is_file($config)) {
                continue;
            }
            $resultConfig = $installer->processConfig(include $config);

            $basepath = dirname(dirname(__DIR__)) . '/config/';
            $configPath = $basepath . implode('/', explode('.', str_replace('.php', '', basename($config))));

            if ( ! is_dir($configPath)) {
                mkdir($configPath, 0777, true);
            }

            $rawConfig = "<?php

/**
 * This file was automatically generated by installer.
 * Feel free to modify it though!
 */

return " . var_export($resultConfig, true) . ";
";
            file_put_contents($configPath . '/local.php', $rawConfig);
        }
    }
}
