<?php

namespace Distr;

use Composer\Script\Event;

class Loader
{
    public static function loadConfigs(Event $event)
    {
        $configs = glob(__DIR__ . '/config/*.php');

        $installer = new Installer($event->getIO());

        foreach ($configs as $config) {
            if ( ! is_file($config)) {
                continue;
            }

            $basepath = dirname(dirname(__DIR__)) . '/config/';
            $configDir = $basepath . implode('/', explode('.', str_replace('.php', '', basename($config))));
            $configFile = $configDir . '/local.php';

            if (file_exists($configFile)) {
                continue;
            }

            $resultConfig = $installer->processConfig(include $config);

            if ( ! is_dir($configDir)) {
                mkdir($configDir, 0777, true);
            }

            $rawConfig = "<?php

/**
 * This file was automatically generated by installer.
 * Feel free to modify it though!
 */

return " . var_export($resultConfig, true) . ";
";
            file_put_contents($configFile, $rawConfig);
        }
    }
}
